name: Backend CI

on:
  push:
    paths:
      - 'backend/**'
  pull_request:
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:  # Ensure this is correctly aligned
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.SQL_PASSWORD }}
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -p3306 --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.19.0'

    - name: Install dependencies
      run: npm install
      working-directory: ./backend

    - name: Initialize Database Schema
      run: mysql -h 127.0.0.1 -u root --password=${{ secrets.SQL_PASSWORD }} test_db < ./database/schema.sql
      

    - name: Run tests
      run: npm run test:ci
      working-directory: ./backend
