name: Backend CI

on:
  push:
    paths:
      - 'backend/**'
  pull_request:
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:  # Ensure this is correctly aligned
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.SQL_PASSWORD }}
          MYSQL_DATABASE: instagramreact
          MYSQL_HOST: ${{ secrets.DB_HOST }}
          MYSQL_USER: ${{ secrets.DB_USER }}
          MYSQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
        ports:
          - 3306/tcp
        options: >-
          --name=mysql-master
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.19.0'

    - name: Install dependencies
      run: npm install
      working-directory: ./backend

    - name: Initialize Database Schema
      run: sudo mysql --host=127.0.0.1 --user=root --password=${{ secrets.SQL_PASSWORD }} instagramreact < ./database/schema.sql

    - name: Verify Database Initialization
      run: |
        echo "SHOW TABLES;" | sudo mysql --host=127.0.0.1 --user=root --password=${{ secrets.SQL_PASSWORD }} instagramreact
        
    - name: Run tests
      run: npm run test:ci
      working-directory: ./backend
      env: 
        MYSQL_HOST: ${{ secrets.DB_HOST }}
        MYSQL_USER: ${{ secrets.DB_USER }}
        MYSQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
        MYSQL_DATABASE: instagramreact